### ISSUE TITLE
Elipse Neon - Generar código de negocio

### ISSUE THREAD

**Issue by goraguta** [UDA-EJIE/uda-ejie.github.io#1]
Egun on,
Hemos instalado el el eclipse Neon para uda en linux, pero no conseguimos generar **código de negocio y control**.

Cuando configuramos la conexión a la BBDD siempre nos da error conexión y tampoco nos sale el botón probar conexión.

¿Sabéis cual puede ser el motivo?, ¿Me podéis ayudar?
![image](https://user-images.githubusercontent.com/2575291/34356707-5fd53220-ea40-11e7-9ecc-276c784f854e.png)

**Comment by xaabi6** [comment]
Hola @goraguta , perdona que te conteste ahora, pero, esta issue la deberías de haber abierto en el apartado correspondiente dentro del repositorio [udaPlugin](https://github.com/UDA-EJIE/udaPlugin/issues). Es por esto que no la habíamos visto, ya que este es el repositorio de la web de UDA y no del plugin.

Dicho esto, hemos tratado de reproducir la issue en una máquina que tenemos con linux (CentOS 7) y nos ha funcionado. Si aún lo sigues necesitando te podría facilitar la versión del plugin que hemos usado.

Un saludo

**Comment by goraguta** [comment]
Si me lo facilitais, fenomenal.

**Comment by goraguta** [comment]
@xaabi6 si me lo facilitáis, fenomenal. Gracias.

**Comment by sergisu** [comment]
Hola, 

A través del siguente enlace podráis descargar el plugin: 
https://drive.google.com/open?id=1C_AhkiKmxZtO2XIdsZyFb1UStmgfiFAy

A ver si te funciona unicamente con la instalación, pero es posible que se deba a un problema con el driver de oracle para acceder a la base de datos que no lo detecta correctamente.
Próximamente liberaremos una nueva versión que incluye modificaciones en el plugin, por lo que igual te merece la pena esperar.

Un saludo.
