### ISSUE TITLE
Conflicto rub_tabs con jQuery 2.12

### ISSUE THREAD

**Issue by Alberto-Geograma-zz** [UDA-EJIE/uda-ejie.github.io#2]
Hola,

Estoy tratando de utilizar un componente rup_tabs para cargar unos contenidos, pero estoy comprobando que cada vez que cambio de pestaña el contenido se recarga y se pierde lo que tenía antes.

Por lo que he visto, rup_tabs utiliza elementos que estaban en jQuery 1.8, pero no están en la versión 1.12. Ejemplos son:

- Se utiliza la opción "ajaxOptions" que ya no existe, por lo que no se llega a indicar que se cargó el panel.

- Cuando se cambia de pestaña, en el evento "select" se accede a "ui.panel", pero el evento no contiene la propiedad "panel", sino las propiedades "newPanel", "newTab", "oldPanel" y "oldTab", por lo que tampoco sería capaz de identificar se la pestaña se cargó o no.

Estoy trabajando con rup 3.4.0

**Comment by xaabi6** [comment]
Hola buenos días @Alberto-Geograma , ya que este proyecto es el dedicado a la web de UDA, ¿podrías abrir esta issue en el apartado correspondiente de [udaRup](https://github.com/UDA-EJIE/udaRUP/issues)?

Un saludo

**Comment by Alberto-Geograma-zz** [comment]
Hecho, muchas gracias.
