### ISSUE TITLE
Varias versiones plugin UDA

### ISSUE THREAD

**Issue by jalvarez1983** [UDA-EJIE/uda-ejie.github.io#3]
En la última versión de Eclipse distribuida (**eclipse_2019-06_UDA_4.2.0.zip**) hay varias versiones del plugin de UDA, lo que hace que no carge el wizard de UDA si no se desinstala previamente la version 4.1.0.

![image](https://user-images.githubusercontent.com/2207608/93471533-c12e4d80-f8f3-11ea-803f-12845a7dc884.png)

**Comment by xaabi6** [comment]
Gracias por avisar, ya está corregido y próximamente estará disponible para su descarga pero con una versión más actual de eclipse, la 2020-03 e incluye también el plugin de la v4.2.2.

**Comment by xaabi6** [comment]
Dejo por aquí un enlace al recién publicado [Eclipse 2020-03 (con plugin v4.2.2)](https://drive.google.com/file/d/1-OUsZoDJALeb933fER9CdErdeZDiwnk9).
