### ISSUE TITLE
Problema al parar Weblogic Eclipse 4.15.0

### ISSUE THREAD

**Issue by jalvarez1983** [UDA-EJIE/uda-ejie.github.io#4]
Hola!

En la última versión distribuida del eclipse (4.15) se produce un error al parar el servidor de aplicaciones (tanto en la versión 10.3.5 o como en la versión 10.3.6).

![image](https://user-images.githubusercontent.com/2207608/102859160-c7205700-442b-11eb-982e-cf3072309d7b.png)

Revisando el Bugzilla de Eclipse, parece que se trata de un error de esta versión:
[https://bugs.eclipse.org/bugs/show_bug.cgi?id=562653](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562653)

Que se corrigió para la siguiente
[https://git.eclipse.org/r/c/platform/eclipse.platform.debug/+/161818/](https://git.eclipse.org/r/c/platform/eclipse.platform.debug/+/161818/)

Para no tener que cambiar referencias a plugins (la solución sería coger la librería org.eclipse.debug.core_3.15.0 de la versión 4.16), hemos modificado el jar actual (org.eclipse.debug.core_3.15.0.v20200224-0654.jar, lo adjunto como un zip pero es el jar, solo cambiar la extensión), de tal forma que solo haría falta sobrescribirlo en la carpeta plugins.

[org.eclipse.debug.core_3.15.0.v20200224-0654.zip](https://github.com/UDA-EJIE/uda-ejie.github.io/files/5728311/org.eclipse.debug.core_3.15.0.v20200224-0654.zip)

Un saludo.

**Comment by xaabi6** [comment]
Probado y funciona perfecto, muchísimas gracias por el aporte.

Voy a incluir el nuevo jar y lo vuelvo a subir.

**Comment by xaabi6** [comment]
Ya está incluida la librería en el eclipse de UDA. Podéis encontrarlo [aquí](https://drive.google.com/file/d/1X_RWizziIBA5Yy1UIyq4k0iz0R5DJ5ek).
