### ISSUE TITLE
Eclipse para UDA en otros SO

### ISSUE THREAD

**Issue by adrianpisabarrogarcia** [UDA-EJIE/uda-ejie.github.io#5]
Hola, somos unos cuantos los que nos gusta trabajar con otros sistemas operativos diferentes a Windows, los recursos proporcionados están explicados para entornos Windows.
¿Habría alguna forma de que nos proporcionáseis el eclipse para MAC y Linux?
He tratado de descargarme la versión que utilizáis desde la web de Eclipse, instalo las Weblogic Tools pero el proceso de configuración del servidor con Eclipse falla, supongo porque es una versión de Eclipse bastante antigua ya.
Aprovecho para hacer otra pregunta, ¿os planteais que funcione un proyecto UDA en IDEs más modernos como Intellij IDEA? La verdad es que facilitaría mucho el desarrollo en UDA. Gracias de antemano.

**Comment by xaabi6** [comment]
Aupa Adrián, disculpa la demora, no había visto la issue.

Originalmente se pensó para funcionar en entornos Windows, pero con el tiempo, sí que ha habido gente que ha usado alguna distro de Linux o macOS con éxito, pero por su cuenta y riesgo, claro. Por mi parte, tengo pendiente montarlo sobre Debian, pero no termino de encontrar el momento por falta de tiempo...

Respecto a la versión de Eclipse, estamos probando la versión **2022-03 (4.23.0)** que podrías usar sin problema alguno, y aunque ya tiene un año, es bastante más moderna que la versión que tenemos liberada actualmente.

Te recomiendo que le eches un vistazo a [esta issue](https://github.com/UDA-EJIE/udaPlugin/issues/8), probablemente te sirva de ayuda para preparar el Eclipse.

Finalmente, decirte que podrías desarrollar aplicaciones UDA en cualquier IDE, salvo cuando tengas que usar el plugin de generación de código, que por el momento, sigue ligado a Eclipse.

Si te surge alguna duda más, puedes preguntar sin problema 😃

**Comment by adrianpisabarrogarcia** [comment]
Gracias Xabi, efectivamente he probado a unir el weblogic 12 con eclipse la versión que me has dicho en un MAC M1 y ha funcionado correctamente. Ahora weblogic va mucho más rápido, comparado con un Windows con Intel. Ahora sí, mira que había probado versiones de Eclipse... ha dado unos cuantos problemas y he tenido que seguir este foro para integrar la weblogic tools, pero ha funcionado: [https://stackoverflow.com/questions/70508100/cannot-install-oracle-weblogic-server-tools-in-eclipse](https://stackoverflow.com/questions/70508100/cannot-install-oracle-weblogic-server-tools-in-eclipse)

Todavía tengo que adaptar bastantes cosas del proyecto en UDA porque sólo esta pensado para entornos Windows, etc.

Mi próximo reto personal será incorporarlo en Intellij para acelerar mucho más el proceso de desarrollo. Aunque esto va a ser aún más complicado...

Ojalá en un futuro se haga una herramienta y externalizar el plugin de generación de código y se actualice más en general el proyecto UDA a los nuevos paradigmas de programación y entornos. Todos los desarrolladores queremos herramientas que nos faciliten la experiencia de desarrollo y se acerquen a las tecnologías del 2023. Aquí me tenéis para lo que necesitéis.

Un abrazo y gracias por todo!
