### ISSUE TITLE
El usr (usr.v1.1.0) para java8

### ISSUE THREAD

**Issue by escaleramen** [UDA-EJIE/uda-ejie.github.io#6]
Buenos días,

me he dispuesto a conformar el entorno de desarrollo para trabajar con la ultima versión de UDA y cuando me he dispuesto a descargar las librerías (usr) de entorno, el link disponible descarga un zip (usr.v1.1.0) con las correspondientes librerías pero para Java 6. No las de Java 8 como correspondería.

¿de donde podría descargarme el usr con las librería para java 8? 

Seria interesante actualizar la documentación para que la descarga de ambas, tipologías, de librerías estaría disponible.

Un saludo y gracias.

**Comment by sergisu** [comment]
Egun on, 

En el uso de xlnets en los entornos java 8, se han modificado las dependencias externas de los artefactos n38.
Contacta con tu referente en Ejie para poder obtener la documentación y los artefactos de actualización necesarios.

Ondo izan.
